// <auto-generated />
using System;
using BarTender.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BarTender.Migrations
{
    [DbContext(typeof(BartenderDBContext))]
    [Migration("20180828011336_Whoops")]
    partial class Whoops
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BarTender.Models.Customization", b =>
                {
                    b.Property<int>("CustomizationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("FrostyMug");

                    b.Property<bool>("HasJuice");

                    b.Property<bool>("IsDouble");

                    b.Property<bool>("LittleUmbrella");

                    b.Property<bool>("SaltyRim");

                    b.Property<bool>("Vegan");

                    b.HasKey("CustomizationId");

                    b.ToTable("Customizations");
                });

            modelBuilder.Entity("BarTender.Models.Drink", b =>
                {
                    b.Property<int>("DrinkId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("DrinkName");

                    b.Property<decimal>("Price");

                    b.HasKey("DrinkId");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("BarTender.Models.DrinkOrder", b =>
                {
                    b.Property<int>("DrinkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomizationId");

                    b.Property<int>("DrinkId");

                    b.Property<DateTime>("TimeOrdered");

                    b.Property<decimal>("TotalPrice");

                    b.HasKey("DrinkOrderId");

                    b.HasIndex("CustomizationId");

                    b.HasIndex("DrinkId");

                    b.ToTable("DrinkOrders");
                });

            modelBuilder.Entity("BarTender.Models.DrinkOrder", b =>
                {
                    b.HasOne("BarTender.Models.Customization", "Customization")
                        .WithMany()
                        .HasForeignKey("CustomizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BarTender.Models.Drink", "OrderedDrink")
                        .WithMany()
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
